### PR TITLE
post-process successful CQL statement executions.

### PR DESCRIPTION
**Pull request by snazy**
This allows extraction and evaluation of data from the result set and conditional execution of further requests by adding information to the Gatling session.

```
  val simpleSelect = cql("simple SELECT")
    .execute("SELECT * FROM test_table WHERE num = ${randomNum}")
    .postProcess( param => param.session.set("foo", param.result.one().getInt("num")) )

...

    feed(feeder)
      .exec(simpleSelect)
      .doIf("${foo}", "42") {
        exec( session => { println("Got 42")
          session } )
      }

```

### CODE REVIEW

**Comment by Mishail** [comment]
We probably could utilize existing Gatling `Check` API http://gatling.io/docs/2.1.7/http/http_check.html to generalize idea of `postprocessors` and `checks` (from #4).

**Comment by snazy** [comment]
Yup - makes sense. Is a bit different since we are dealing with a result set that could possibly consist of a huge number of rows and use paging to fetch them - but feels doable.

**Comment by snazy** [comment]
Note: the latest commit is NOT ready. Just some experiment how it may look.

**Comment by snazy** [comment]
Reverted to post-process stuff (just in case). But opened #8 for check-API. Feel free to close this one :)

**Comment by snazy** [comment]
superseded by #8

**Pull request closed without merging**
