### PR TITLE
[#12] Gatling 2.2.3

### PR DESCRIPTION
**Pull request by Mishail**
@snazy what do you think?

### CODE REVIEW

**Comment by snazy** [comment]
yea - the annoying thing with Gatling is the breaking API changes in minor versions.

**Comment by slandelle** [comment]
@snazy No offense, but the real problem is what you call API we call internals.

**Comment by snazy** [comment]
@slandelle, i get your point. Just, I think it's stuff that you actually need to build something like GatlingCql. (Not offended ;) )

**Comment by slandelle** [comment]
@snazy The story is that we're not confident in having those stable atm, hence they're not API. Proof is we indeed change them a lot.
And we just don't have the cycles to keep a close eye on community/third party projects.
The only way for us to do that would be if you were to donate this code to Gatling (which has its cons too, like IP donation, being bound to our release cycle).

**Pull request merged**
